FROM python:3.11-slim
WORKDIR /app
COPY requirements-serve.txt .
RUN pip install --no-cache-dir -r requirements-serve.txt
COPY src/serve.py .
COPY src/utils.py .
EXPOSE 9001
CMD ["python", "serve.py"]
