apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: material-consumption-serving
  annotations:
    scenarios.ai.sap.com/id: "material-consumption"
    scenarios.ai.sap.com/name: "material-consumption"
    scenarios.ai.sap.com/description: "Serving template for material consumption prediction"
    executables.ai.sap.com/name: "consumption-serving"
    executables.ai.sap.com/description: "Serves predictions for material consumption"
  labels:
    ai.sap.com/version: "0.0.1"
    scenarios.ai.sap.com/id: "material-consumption"
spec:
  inputs:
    artifacts:
      - name: trained_model
  imagePullSecrets:
    - name: docker-registry-secret
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1"
      labels: |
        ai.sap.com/resourcePlan: "starter"
    spec: |
      predictor:
        containers:
          - name: kserve-container
            image: docker.io/cguevara962/consumption-serve:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 9001
                protocol: TCP
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.trained_model}}"
